# Generated by Django 2.2.5 on 2019-09-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcategoria', '0001_initial'),
        ('habilidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('universo', models.CharField(max_length=50, verbose_name='Universo')),
                ('categoria_heroi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='hcategoria.Categoria', verbose_name='categoria')),
                ('habilidade_heroi', models.ManyToManyField(to='habilidade.Habilidade', verbose_name='habilidade')),
            ],
        ),
    ]
