# Generated by Django 2.2.5 on 2019-09-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroi',
            name='universo',
        ),
        migrations.AlterField(
            model_name='heroi',
            name='habilidade_heroi',
            field=models.ManyToManyField(to='habilidade.Habilidade', verbose_name='habilidades'),
        ),
    ]
