# Generated by Django 2.2.5 on 2019-09-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0001_initial'),
        ('heroi', '0002_auto_20190930_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroi',
            name='universo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universo.Universo'),
            preserve_default=False,
        ),
    ]
