# Generated by Django 2.2.5 on 2019-09-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroi', '0003_heroi_universo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroi',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universo', to='universo.Universo', verbose_name='universo'),
        ),
    ]
